### ISSUE TITLE
Kernel not connecting

### ISSUE THREAD

**Issue by kurofuneparry** [dataquestio/ds-containers#2]
I was able to follow the directions [here](https://www.dataquest.io/blog/data-science-ec2-quickstart/) to install this on a Digital Ocean server. The Jupyter website was able to load, but when I tried to start a notebook I got the following error message.

> A connection to the notebook server could not be established. The notebook will continue trying to reconnect, but until it does, you will NOT be able to run code. Check your network connection or notebook server configuration.

It seems that the backend kernel is not connecting. Does this feature work? What can I do to get it working?

Thank you very much.

**Comment by VikParuchuri** [comment]
Yup -- we originally missed a few lines in the nginx config file.  It should look like this:

```
server {
       listen         80;
       return         301 https://$host$request_uri;
}

server {

    set $custom_host $host;
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    client_max_body_size 10M;

    location / {
        proxy_set_header Host $custom_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Protocol $scheme;

        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Origin "";

        proxy_pass http://127.0.0.1:8888;
    }
}
```

The addition of these lines is critical:

```
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Origin "";
```

Does your `/etc/nginx/sites-enabled/ds` file match the above?

**Comment by kurofuneparry** [comment]
This solved my problem. Thank you and have a nice day.
