### ISSUE TITLE
Where is ubuntu-base?

### ISSUE THREAD

**Issue by KyleGobel** [dataquestio/ds-containers#3]
Hey, sorry for dumb question (I don't know much about docker), was just looking at the way you built up the containers, and see the initial one the starters use is ubuntu-base.  I see it on docker hub but there's no Dockerfile, and I don't see it in the repo anywhere.

**Comment by ericuni** [comment]
I want to know the ubuntu-base too. And I dit the same thing just like you trying to find it in Docker hub.

**Comment by ghost** [comment]
Any way we can see the docker hub file for ubuntu-base? This is a great image by the way... the top one i use when doing python stuff for my school experiments.

**Comment by jaypeedevlin** [comment]
Hey guys, sorry for the delayed reply - `ubuntu-base` is an old one we've decommissioned everywhere except here.

We're very close to updating these containers, and the new versions will be built off `ubuntu:16.04`
